### PR TITLE
Add a setup.py with bad parse_requirements

### PR DESCRIPTION
**Pull request by ericanders-wf**
this setup.py should make srcclr fail

### CODE REVIEW

**Comment by ericanders-wf** [comment]
## Osprey

SourceClear Results:
- The scan returned 0 results

**Comment by ericanders-wf** [comment]
## Osprey
Issues Identified in 3rd Party Libraries:
* The scan returned no results

## Raven
Number of Findings: 0

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by infosec-wf** [comment]
## Raven

Number of Findings: 0

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Pull request closed without merging**
