### PR TITLE
Good setup testing - test Osprey

### PR DESCRIPTION
**Pull request by ericanders-wf**

### CODE REVIEW

**Comment by infosec-wf** [comment]
## Raven

Number of Findings: 0

## Osprey

Issues Identified in 3rd Party Libraries:
- The scan returned no results

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Pull request closed without merging**
