### PR TITLE
Good setup testing again

### PR DESCRIPTION
**Pull request by ericanders-wf**
now with logs?

### CODE REVIEW

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by infosec-wf** [comment]
## Raven
Number of Findings: 0


## Osprey
Issues Identified in 3rd Party Libraries:
* High Vulnerabilities: 0
* Medium Vulnerabilities: 3
* Low Vulnerabilities: 1

See InfoSec Team for Details

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
## Raven
Number of Findings: 0


## Osprey
Issues Identified in 3rd Party Libraries:
* High Vulnerabilities: 0
* Medium Vulnerabilities: 3
* Low Vulnerabilities: 1

See InfoSec Team for Details

**Comment by ericanders-wf** [comment]
@aviary-wf

**Pull request closed without merging**
