### PR TITLE
Bad setup testing

### PR DESCRIPTION
**Pull request by ericanders-wf**
this should fail (osprey) and pass the overall scan

### CODE REVIEW

**Comment by infosec-wf** [comment]
## Raven
Number of Findings: 0

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Pull request closed without merging**
