### PR TITLE
Good setup testing

### PR DESCRIPTION
**Pull request by ericanders-wf**
Testing with a good setup.py and requirements with vulnerabilities.

### CODE REVIEW

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by infosec-wf** [comment]
## Raven
Number of Findings: 0

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Comment by ericanders-wf** [comment]
@aviary-wf

**Pull request closed without merging**
